apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicddemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cicddemo
  template:
    metadata:
      labels:
        app: cicddemo
    spec:
      containers:
        - name: cicddemo
          image: andreutza/cicddemo
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: cicddemo-service
  annotations:
    # Specify the load balancer scheme as internet-facing to create a public-facing Network Load Balancer (NLB)
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  selector:
    app: cicddemo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
